// eslint-disable-next-line import/prefer-default-export
export const initialState = {
  campaigns: null,
  isLoadingCampaigns: false,
  isDeleting: false,
  isBotDeleting: false,
  isLoadingBots: false,
  isLoadingBot: false,
  updatedBot: false,
  duplicateId: null,
  bots: null,
  shoutouts: null,
  isLoadingShoutouts: false,
  updatedShoutouts: false,
  isShoutoutDeleting: false,
  duplicateIdCampaign: null,
  isLoadingShoutout: false,
  updatedShoutout: false,
  duplicateIdShoutout: null,
  isLoadingBoosts: false,
  boosts: null,
  updatedBoosts: null,
  activatedBoostId: null,
  isActivatedReminder: false,
  isLoadingReminders: false,
  reminders: null,
  updatedReminder: false,
  points: null
}
