import * as icons from '@fortawesome/free-solid-svg-icons'
import { faStar as faEmptyStar } from '@fortawesome/free-regular-svg-icons'

const getIconByType = type => {
  switch (type) {
    case 'Add':
      return icons.faPlus
    case 'Calendar':
      return icons.faCalendarAlt
    case 'Copy':
      return icons.faCopy
    case 'Delete':
      return icons.faTimes
    case 'DeleteData':
      return icons.faUserTimes
    case 'DeleteTrash':
      return icons.faTrashAlt
    case 'Dollar':
      return icons.faDollarSign
    case 'Equal':
      return icons.faEquals
    case 'File':
      return icons.faFileAlt
    case 'NotEqual':
      return icons.faNotEqual
    case 'Rotate':
      return icons.faRedoAlt
    case 'RotateLeft':
      return icons.faUndoAlt
    case 'List':
      return icons.faList
    case 'Download':
      return icons.faDownload
    case 'Warning':
      return icons.faExclamationCircle
    case 'Eye':
      return icons.faEye
    case 'Star':
      return icons.faStar
    case 'StarHalf':
      return icons.faStarHalfAlt
    case 'StarEmpty':
      return faEmptyStar
    case 'InfoCircle':
      return icons.faInfoCircle
    case 'PlusCircle':
      return icons.faPlusCircle
    case 'SearchPlus':
      return icons.faSearchPlus
    case 'Search':
      return icons.faSearch
    case 'Save':
      return icons.faSave
    case 'Minus':
      return icons.faMinus
    case 'ArrowLeft':
      return icons.faChevronLeft
    case 'ArrowRight':
      return icons.faChevronRight
    case 'ArrowUp':
      return icons.faArrowUp
    case 'ArrowDown':
      return icons.faArrowDown
    case 'PhoneVolume':
      return icons.faPhoneVolume
    case 'Email':
      return icons.faEnvelope
    case 'Configuration':
      return icons.faCogs
    case 'Edit':
      return icons.faEdit
    case 'MapMarker':
      return icons.faMapMarker
    case 'SortAsc':
      return icons.faSortAlphaUp
    case 'SortDesc':
      return icons.faSortAlphaDown
    case 'Barcode':
      return icons.faBarcode
    case 'Sort':
      return icons.faSort
    case 'SignOut':
      return icons.faSignOutAlt
    case 'Check':
      return icons.faCheckSquare
    case 'Exchange':
      return icons.faExchangeAlt
    case 'Refresh':
      return icons.faSync
    case 'Interaction':
      return icons.faShareAlt
    case 'Reject':
      return icons.faBan
    case 'Tasks':
      return icons.faTasks
    case 'Globe':
      return icons.faGlobeAmericas
    case 'Reward':
      return icons.faTrophy
    case 'User':
      return icons.faUser
    case 'UserReject':
      return icons.faUserTimes
    case 'Pdf':
      return icons.faFilePdf
    case 'Budget':
      return icons.faCalculator
    case 'Close':
      return icons.faTimes
    default:
      return icons.faPlus
  }
}

export default getIconByType
